"""empty message

Revision ID: 30db2293ca83
Revises: d8a87121b5e2
Create Date: 2018-12-16 23:08:05.107696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30db2293ca83'
down_revision = 'd8a87121b5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_book_review', 'review', ['user_id', 'book_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_book_review', 'review', type_='unique')
    # ### end Alembic commands ###
