"""empty message

Revision ID: d8a87121b5e2
Revises: a91dfca3739f
Create Date: 2018-12-16 19:36:23.395374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a87121b5e2'
down_revision = 'a91dfca3739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating', sa.Integer(), nullable=False))
    op.drop_column('review', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('review', 'rating')
    # ### end Alembic commands ###
